"""Initial fresh migration

Revision ID: d934500ae8a1
Revises: 
Create Date: 2025-08-27 11:29:13.735407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd934500ae8a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('fotoprofile', sa.String(length=250), nullable=True),
    sa.Column('path', sa.String(length=250), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('master_buku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(length=250), nullable=False),
    sa.Column('pengarang', sa.String(length=250), nullable=False),
    sa.Column('penerbitan', sa.String(length=250), nullable=False),
    sa.Column('deskripsi', sa.String(length=250), nullable=False),
    sa.Column('isbn', sa.String(length=100), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('kota', sa.String(length=250), nullable=False),
    sa.Column('tahun_terbit', sa.String(length=250), nullable=False),
    sa.Column('editor', sa.String(length=250), nullable=False),
    sa.Column('ilustrator', sa.String(length=250), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('kategori', sa.Enum('Diolah', 'Disumbangkan', name='kategori'), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('cover_buku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_buku_id', sa.Integer(), nullable=False),
    sa.Column('cover', sa.String(length=250), nullable=False),
    sa.Column('path', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['master_buku_id'], ['master_buku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sinopsis_buku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sinopsis', sa.Text(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('no_class', sa.String(length=250), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('master_buku_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_buku_id'], ['master_buku.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_buku_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sinopsis_buku')
    op.drop_table('cover_buku')
    op.drop_table('master_buku')
    op.drop_table('user')
    # ### end Alembic commands ###
